### PR TITLE
Incomplete CLI Arguments

### PR DESCRIPTION
**Pull request by jwrb**
## WIP

This should allow the passing of username & password for the Paycoin server.

Port, Host & Entire Config file passing is still challenging, as Ruby imposes some system file access restrictions. I hope to have this working soon however.

### CODE REVIEW

**Comment by ligerzero459** [comment]
The 'os' gem could help you determine the absolute path by OS so you can avoid Ruby's interesting relative path behavior

https://github.com/rdp/os

**Comment by jwrb** [comment]
Sounds good @ligerzero459. Relative paths seem to have been my issue with testing earlier today.

**Comment by jwrb** [comment]
Added. Should load default files if no custom config file has been specified on application runtime

**Comment by ligerzero459** [comment]
Tested on Linux, Mac and Windows. Worked perfectly, thanks!

**Pull request merged**
